// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using shopping_api.Data;

#nullable disable

namespace shopping_api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("shopping_api.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<string>("product")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            price = 100,
                            product = "Shoes"
                        },
                        new
                        {
                            id = 2,
                            price = 200,
                            product = "Pants"
                        },
                        new
                        {
                            id = 3,
                            price = 300,
                            product = "Shirt"
                        },
                        new
                        {
                            id = 4,
                            price = 400,
                            product = "Watch"
                        },
                        new
                        {
                            id = 5,
                            price = 500,
                            product = "Necklace"
                        });
                });

            modelBuilder.Entity("shopping_api.Models.ProductList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("productid")
                        .HasColumnType("integer");

                    b.Property<int>("total_price")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("productid");

                    b.ToTable("product_list");
                });

            modelBuilder.Entity("shopping_api.Models.ProductList", b =>
                {
                    b.HasOne("shopping_api.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("productid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });
#pragma warning restore 612, 618
        }
    }
}
