# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.7'

services:
  db:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: example
    
    networks:
      - shop-network

  shopping-api:
    image: bitbyteyum/api:v1
    build:
      context: .
      dockerfile: shopping-api/Dockerfile
    ports:
      - 5000:5000
    links:
      - db
    depends_on:
      - 'db'
    networks:
      - shop-network

  react-aoo:
    image: bitbyteyum/app:v1
    build:
        context: .
        dockerfile: react-app/Dockerfile
    
    ports:
      - 80:80
    depends_on:
      - 'shopping-api'
  
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge

